#!/bin/bash
for branch in `git branch -r | grep -v HEAD | grep -v master`; do
    echo "git checkout ${branch##*/}"
    git checkout master
    git checkout ${branch##*/}
    git pull --ff-only
done
git checkout master
